defaults:
  - model: lightcnn
  - writer: noop
  - metrics: asvspoof
  - datasets: asvspoof
  - dataloader: main
  - transforms: asvspoof
  - _self_

optimizer:
  _target_: torch.optim.Adam
  lr: 1e-4
  weight_decay: 1e-4

lr_scheduler: null

loss_function:
  _target_: src.loss.ASoftmaxLoss
  lambda_max: 1000.0
  lambda_min: 5.0
  lambda_decay: 0.1

balanced_sampling: true

dataloader:
  batch_size: 4
  num_workers: 0
  pin_memory: false

trainer:
  log_step: 500
  n_epochs: 100
  epoch_len: null
  device_tensors: ["audio", "labels"]
  resume_from: null
  device: auto
  override: false
  monitor: "min dev_EER"
  save_period: 1
  early_stop: 15
  save_dir: "saved"
  seed: 1
  skip_oom: true
  max_grad_norm: 5.0
  use_data_parallel: true
