defaults:
  - model: lightcnn
  - metrics: asvspoof
  - datasets: asvspoof_eval
  - dataloader: main
  - transforms: asvspoof
  - _self_
inferencer:
  device_tensors: ["audio", "labels"]
  device: auto # device name or "auto"
  save_path: "asvspoof" # any name here, can be a dataset name
  save_individual_predictions: false
  seed: 1
  from_pretrained: "saved/asvspoof_lcnn/model_best.pth"

dataloader:
  batch_size: 4
  num_workers: 2
  pin_memory: true
